core/config/routes.rb
Spree::Core::Engine.routes.draw do

  root :to => 'home#index'

  resources :products

  match '/locale/set', :to => 'locale#set'

  resources :tax_categories

  resources :states, :only => :index

  # non-restful checkout stuff
  match '/checkout/update/:state', :to => 'checkout#update', :as => :update_checkout
  match '/checkout/:state', :to => 'checkout#edit', :as => :checkout_state
  match '/checkout', :to => 'checkout#edit', :state => 'address', :as => :checkout

  resources :orders do
    post :populate, :on => :collection

    resources :line_items
    resources :creditcards
    resources :creditcard_payments

    resources :shipments do
      member do
        get :shipping_method
      end
    end

  end
  get '/cart', :to => 'orders#edit', :as => :cart
  put '/cart', :to => 'orders#update', :as => :update_cart
  put '/cart/empty', :to => 'orders#empty', :as => :empty_cart

  resources :shipments do
    member do
      get :shipping_method
      put :shipping_method
    end
  end

  #   # Search routes
  match 's/*product_group_query', :to => 'products#index', :as => :simple_search
  match '/pg/:product_group_name', :to => 'products#index', :as => :pg_search
  match '/t/*id/s/*product_group_query', :to => 'taxons#show', :as => :taxons_search
  match 't/*id/pg/:product_group_name', :to => 'taxons#show', :as => :taxons_pg_search

  #   # route globbing for pretty nested taxon and product paths
  match '/t/*id', :to => 'taxons#show', :as => :nested_taxons
  #
  #   #moved old taxons route to after nested_taxons so nested_taxons will be default route
  #   #this route maybe removed in the near future (no longer used by core)
  #   map.resources :taxons
  #

  namespace :admin do
    resources :adjustments
    resources :zones
    resources :users do
      member do
        post :dismiss_banner
      end
    end
    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories
    resources :configurations, :only => :index
    resources :products do
      resources :product_properties
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
      resources :option_types do
        member do
          get :select
          get :remove
        end
        collection do
          get :available
          get :selected
          post :update_positions
        end
      end
      resources :taxons do
        member do
          get :select
          delete :remove
        end
        collection do
          post :available
          post :batch_select
          get  :selected
        end
      end
    end
    resources :option_types do
      collection do
        post :update_positions
      end
    end

    resources :properties do
      collection do
        get :filtered
      end
    end

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resource :inventory_settings
    resources :google_analytics

    resources :orders do
      member do
        put :fire
        get :fire
        post :resend
        get :history
      end

      resource :customer, :controller => "orders/customer_details"

      resources :adjustments
      resources :line_items
      resources :shipments do
        member do
          put :fire
        end
      end
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end
      end
    end

    resource :general_settings do
      collection do
        post :dismiss_alert
      end
    end

    resources :taxonomies do
      member do
        get :get_children
      end

      resources :taxons
    end

    resources :reports, :only => [:index, :show] do
      collection do
        get :sales_total
      end
    end

    resources :shipments
    resources :shipping_methods
    resources :shipping_categories
    resources :tax_rates
    resource  :tax_settings
    resources :calculators
    resources :product_groups do
      resources :product_scopes
    end


    resources :trackers
    resources :payment_methods
    resources :mail_methods do
      member do
        post :testmail
      end
    end
  end

  match '/admin', :to => 'admin/orders#index', :as => :admin

  match '/content/cvv', :to => 'content#cvv'
  match '/content/*path', :to => 'content#show', :via => :get, :as => :content
end

core/app/models/spree/adjustment.rb
# Adjustments represent a change to the +item_total+ of an Order.  Each adjustment has an +amount+ that be either
# positive or negative.  Adjustments have two useful boolean flags
#
# +mandatory+
#
# If this flag is set to true then it means the the charge is required and will not be removed from the
# order, even if the amount is zero.  In other words a record will be created even if the amount is zero.
# This is  useful for representing things such as shipping and tax charges where you may want to make it explicitly
# clear that no charge was made for such things.
#
# +locked+
#
# The charge is never to be udpated.  Typically you would want to freeze certain adjustments after checkout.
# One use case for this is if you want to lock a shipping adjustment so that its value does not change
# in the future when making other trivial edits to the order (like an email change).
#
# +eligible?+
#
#  This boolean attributes stores whether this adjustment is currently eligible for its order. Only eligible
#  adjustments count towards the order's adjustment total. This allows an adjustment to be preserved if it
#  becomes ineligible so it might be reinstated.
#
module Spree
  class Adjustment < ActiveRecord::Base
    belongs_to :adjustable, :polymorphic => true
    belongs_to :source, :polymorphic => true
    belongs_to :originator, :polymorphic => true

    validates :label, :presence => true
    validates :amount, :numericality => true

    scope :tax, lambda { where(:originator_type => 'Spree::TaxRate', :adjustable_type => 'Spree::Order') }
    scope :price, lambda { where(:adjustable_type => 'Spree::LineItem') }
    scope :shipping, lambda { where(:label => I18n.t(:shipping)) }
    scope :optional, where(:mandatory => false)
    scope :eligible, where(:eligible => true)
    scope :charge, where("amount >= 0")
    scope :credit, where("amount < 0")

    after_save :update_adjustable
    after_destroy :update_adjustable

    # Update the boolean _eligible_ attribute which deterimes which adjustments count towards the order's
    # adjustment_total.
    def set_eligibility
      update_attribute_without_callbacks(:eligible,
                                         mandatory ||
                                         (amount != 0 && eligible_for_originator?))
    end

    # Allow originator of the adjustment to perform an additional eligibility of the adjustment
    # Should return _true_ if originator is absent or doesn't implement _eligible?_
    def eligible_for_originator?
      return true if originator.nil?
      !originator.respond_to?(:eligible?) || originator.eligible?(source)
    end

    # Update both the eligibility and amount of the adjustment. Adjustments delegate updating of amount to their Originator
    # when present, but only if +locked+ is false.  Adjustments that are +locked+ will never change their amount.
    # The new adjustment amount will be set by by the +originator+ and is not automatically saved.  This makes it save
    # to use this method in an after_save hook for other models without causing an infinite recursion problem.
    #
    # order#update_adjustments passes self as the src, this is so calculations can be performed on the
    # current values. If we used source it would load the old record from db for the association
    def update!(src = nil)
      src ||= source
      return if locked?
      if originator.present?
        originator.update_adjustment(self, src)
      end
      set_eligibility
    end

    private

    def update_adjustable
      adjustable.update! if adjustable.is_a? Order
    end

  end
end

core/app/controllers/spree/admin/adjustments_controller.rb
module Spree
  module Admin
    class AdjustmentsController < ResourceController
      belongs_to 'spree/order', :find_by => :number
      destroy.after :reload_order

      private
        def reload_order
          @order.reload
        end
    end
  end
end

core/app/views/spree/admin/adjustments/_adjustments_table.html.erb
<table class="index" data-hook="adjustments">
  <tr data-hook="adjustmment_head">
    <th><%= "#{t('spree.date')}/#{t('spree.time')}" %></th>
    <th><%= t(:description) %></th>
    <th><%= t(:amount) %></th>
    <th></th>
  </tr>
  <% @order.adjustments.each do |adjustment|
       @edit_url = edit_admin_order_adjustment_path(@order, adjustment)
       @delete_url = admin_order_adjustment_path(@order, adjustment)
  %>
    <tr id="<%= dom_id(adjustment) %>" data-hook="adjustment_row">
      <td><%= adjustment.created_at.to_s(:date_time24) %></td>
      <td><%= adjustment.label %></td>
      <td><%= number_to_currency adjustment.amount %></td>
      <td class='actions'>
        <%= link_to_edit adjustment, :class => 'edit' %>
        &nbsp;
        <%= link_to_delete adjustment, {}, :class => 'delete' %>
      </td>

    </tr>
  <% end %>
</table>

core/app/views/spree/admin/adjustments/_form.html.erb
<%= f.field_container :amount do %>
  <%= f.label :amount, t(:amount) %> <span class="required">*</span><br />
  <%= text_field :adjustment, :amount, {:style => 'width:80px;'} %>
  <%= f.error_message_on :amount %>
<% end %>

<%= f.field_container :label do %>
  <%= f.label :label, t(:description) %> <span class="required">*</span><br />
  <%= text_field :adjustment, :label, {:style => 'width:180px;'} %>
  <%= f.error_message_on :label %>
<% end %>

core/app/views/spree/admin/adjustments/edit.html.erb
<%= render :partial => 'spree/admin/shared/order_tabs', :locals => { :current => 'Adjustments' } %>

<h2><%= t(:adjustment) %></h2>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @adjustment } %>
<%= form_for @adjustment, :url => admin_order_adjustment_path(@order, @adjustment), :method => :put do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>

  <p class="form-buttons" data-hook="buttons">
    <%= button t(:continue) %>
    <%= t(:or) %> <%= link_to t('actions.cancel'), admin_order_adjustments_url(@order) %>
  </p>
<% end %>

core/app/views/spree/admin/adjustments/index.html.erb
<%= render :partial => 'spree/admin/shared/new_adjustment_button' %>
<%= render :partial => 'spree/admin/shared/order_tabs', :locals => { :current => 'Adjustments' } %>
<%= render :partial => 'adjustments_table' %>
<%= button_link_to t(:continue), @order.cart? ? new_admin_order_payment_url(@order) : admin_orders_url %>

core/app/views/spree/admin/adjustments/new.html.erb
<%= render :partial => 'spree/admin/shared/order_tabs', :locals => { :current => 'Adjustments' } %>

<h2><%= t(:new_adjustment) %></h2>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @adjustment } %>

<%= form_for @adjustment, :url => admin_order_adjustments_path do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>

  <p class="form-buttons" data-hook="buttons">
    <%= button t(:continue) %>
    <%= t(:or) %> <%= link_to t('actions.cancel'), admin_order_adjustments_url(@order) %>
  </p>
<% end %>