core/config/routes.rb
Spree::Core::Engine.routes.draw do

  root :to => 'home#index'

  resources :products

  match '/locale/set', :to => 'locale#set'

  resources :tax_categories

  resources :states, :only => :index

  # non-restful checkout stuff
  match '/checkout/update/:state', :to => 'checkout#update', :as => :update_checkout
  match '/checkout/:state', :to => 'checkout#edit', :as => :checkout_state
  match '/checkout', :to => 'checkout#edit', :state => 'address', :as => :checkout

  resources :orders do
    post :populate, :on => :collection

    resources :line_items
    resources :creditcards
    resources :creditcard_payments

    resources :shipments do
      member do
        get :shipping_method
      end
    end

  end
  get '/cart', :to => 'orders#edit', :as => :cart
  put '/cart', :to => 'orders#update', :as => :update_cart
  put '/cart/empty', :to => 'orders#empty', :as => :empty_cart

  resources :shipments do
    member do
      get :shipping_method
      put :shipping_method
    end
  end

  #   # Search routes
  match 's/*product_group_query', :to => 'products#index', :as => :simple_search
  match '/pg/:product_group_name', :to => 'products#index', :as => :pg_search
  match '/t/*id/s/*product_group_query', :to => 'taxons#show', :as => :taxons_search
  match 't/*id/pg/:product_group_name', :to => 'taxons#show', :as => :taxons_pg_search

  #   # route globbing for pretty nested taxon and product paths
  match '/t/*id', :to => 'taxons#show', :as => :nested_taxons
  #
  #   #moved old taxons route to after nested_taxons so nested_taxons will be default route
  #   #this route maybe removed in the near future (no longer used by core)
  #   map.resources :taxons
  #

  namespace :admin do
    resources :adjustments
    resources :zones
    resources :users do
      member do
        post :dismiss_banner
      end
    end
    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories
    resources :configurations, :only => :index
    resources :products do
      resources :product_properties
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
      resources :option_types do
        member do
          get :select
          get :remove
        end
        collection do
          get :available
          get :selected
          post :update_positions
        end
      end
      resources :taxons do
        member do
          get :select
          delete :remove
        end
        collection do
          post :available
          post :batch_select
          get  :selected
        end
      end
    end
    resources :option_types do
      collection do
        post :update_positions
      end
    end

    resources :properties do
      collection do
        get :filtered
      end
    end

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resource :inventory_settings
    resources :google_analytics

    resources :orders do
      member do
        put :fire
        get :fire
        post :resend
        get :history
      end

      resource :customer, :controller => "orders/customer_details"

      resources :adjustments
      resources :line_items
      resources :shipments do
        member do
          put :fire
        end
      end
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end
      end
    end

    resource :general_settings do
      collection do
        post :dismiss_alert
      end
    end

    resources :taxonomies do
      member do
        get :get_children
      end

      resources :taxons
    end

    resources :reports, :only => [:index, :show] do
      collection do
        get :sales_total
      end
    end

    resources :shipments
    resources :shipping_methods
    resources :shipping_categories
    resources :tax_rates
    resource  :tax_settings
    resources :calculators
    resources :product_groups do
      resources :product_scopes
    end


    resources :trackers
    resources :payment_methods
    resources :mail_methods do
      member do
        post :testmail
      end
    end
  end

  match '/admin', :to => 'admin/orders#index', :as => :admin

  match '/content/cvv', :to => 'content#cvv'
  match '/content/*path', :to => 'content#show', :via => :get, :as => :content
end

core/app/models/spree.rb
module Spree
  def self.table_name_prefix
    'spree_'
  end
end

core/app/models/spree/activator.rb
module Spree
  class Activator < ActiveRecord::Base
    cattr_accessor :event_names

    self.event_names = [
      'spree.cart.add',
      'spree.order.contents_changed',
      'spree.user.signup'
    ]

    def self.register_event_name(name)
      self.event_names << name
    end

    scope :event_name_starts_with, lambda{ |name| where('event_name LIKE ?', "#{name}%") }
    scope :active, where('(starts_at IS NULL OR starts_at < ?) AND (expires_at IS NULL OR expires_at > ?)', Time.now, Time.now)

    def activate(payload)
    end

    def expired?
      starts_at && Time.now < starts_at ||
      expires_at && Time.now > expires_at
    end
  end
end

core/app/models/spree/address.rb
module Spree
  class Address < ActiveRecord::Base
    belongs_to :country
    belongs_to :state

    has_many :shipments

    validates :firstname, :lastname, :address1, :city, :zipcode, :country, :phone, :presence => true
    validate :state_validate

    # disconnected since there's no code to display error messages yet OR matching client-side validation
    def phone_validate
      return if phone.blank?
      n_digits = phone.scan(/[0-9]/).size
      valid_chars = (phone =~ /^[-+()\/\s\d]+$/)
      if !(n_digits > 5 && valid_chars)
        errors.add(:phone, :invalid)
      end
    end

    def state_validate
      #skip state validation without country (also required)
      #or when disabled by perfernce
      return if self.country_id.blank? || !Spree::Config[:address_requires_state]

      #ensure associated state belongs to country
      if self.state_id.present?
        if self.state.country_id == self.country_id
          self.state_name = nil #not required as we have a valid state and country combo
        else
          if self.state_name.present?

            self.state_id = nil
          else
            errors.add(:state, :invalid)
          end
        end
      end

      #ensure state_name belongs to country without states, or that it matches a predefined state name/abbr
      if self.state_name.present?
        if country.states.present?
          states = country.states.find_all_by_name_or_abbr(self.state_name)

          if states.size == 1
            self.state = states.first
            self.state_name = nil
          else
            errors.add(:state, :invalid)
          end
        end
      end

      #ensure at least one state field is populated
      if self.state_id.blank? && self.state_name.blank?
        errors.add(:state, :blank)
      end

    end

    def self.default
      new :country_id => Spree::Config[:default_country_id]
    end

    # can modify an address if it's not been used in an order (but checkouts controller has finer control)
    # def editable?
    #   new_record? || (shipments.empty? && checkouts.empty?)
    # end

    def full_name
      self.firstname + ' ' + self.lastname
    end

    def state_text
      state.nil? ? state_name : (state.abbr.blank? ? state.name : state.abbr)
    end

    def zone
      (state && state.zone) ||
      (country && country.zone)
    end

    def zones
      Zone.match(self)
    end

    def same_as?(other)
      return false if other.nil?
      attributes.except('id', 'updated_at', 'created_at') ==  other.attributes.except('id', 'updated_at', 'created_at')
    end

    alias same_as same_as?

    def to_s
      "#{full_name}: #{address1}"
    end

    def clone
      self.class.new(self.attributes.except('id', 'updated_at', 'created_at'))
    end

    def ==(other_address)
      self_attrs = self.attributes
      other_attrs = other_address.respond_to?(:attributes) ? other_address.attributes : {}

      [self_attrs, other_attrs].each { |attrs| attrs.except!('id', 'created_at', 'updated_at', 'order_id') }

      self_attrs == other_attrs
    end

    def empty?
      attributes.except('id', 'created_at', 'updated_at', 'order_id', 'country_id').all? { |_, v| v.nil? }
    end
  end
end

core/app/models/spree/adjustment.rb
# Adjustments represent a change to the +item_total+ of an Order.  Each adjustment has an +amount+ that be either
# positive or negative.  Adjustments have two useful boolean flags
#
# +mandatory+
#
# If this flag is set to true then it means the the charge is required and will not be removed from the
# order, even if the amount is zero.  In other words a record will be created even if the amount is zero.
# This is  useful for representing things such as shipping and tax charges where you may want to make it explicitly
# clear that no charge was made for such things.
#
# +locked+
#
# The charge is never to be udpated.  Typically you would want to freeze certain adjustments after checkout.
# One use case for this is if you want to lock a shipping adjustment so that its value does not change
# in the future when making other trivial edits to the order (like an email change).
#
# +eligible?+
#
#  This boolean attributes stores whether this adjustment is currently eligible for its order. Only eligible
#  adjustments count towards the order's adjustment total. This allows an adjustment to be preserved if it
#  becomes ineligible so it might be reinstated.
#
module Spree
  class Adjustment < ActiveRecord::Base
    belongs_to :adjustable, :polymorphic => true
    belongs_to :source, :polymorphic => true
    belongs_to :originator, :polymorphic => true

    validates :label, :presence => true
    validates :amount, :numericality => true

    scope :tax, lambda { where(:originator_type => 'Spree::TaxRate', :adjustable_type => 'Spree::Order') }
    scope :price, lambda { where(:adjustable_type => 'Spree::LineItem') }
    scope :shipping, lambda { where(:label => I18n.t(:shipping)) }
    scope :optional, where(:mandatory => false)
    scope :eligible, where(:eligible => true)
    scope :charge, where("amount >= 0")
    scope :credit, where("amount < 0")

    after_save :update_adjustable
    after_destroy :update_adjustable

    # Update the boolean _eligible_ attribute which deterimes which adjustments count towards the order's
    # adjustment_total.
    def set_eligibility
      update_attribute_without_callbacks(:eligible,
                                         mandatory ||
                                         (amount != 0 && eligible_for_originator?))
    end

    # Allow originator of the adjustment to perform an additional eligibility of the adjustment
    # Should return _true_ if originator is absent or doesn't implement _eligible?_
    def eligible_for_originator?
      return true if originator.nil?
      !originator.respond_to?(:eligible?) || originator.eligible?(source)
    end

    # Update both the eligibility and amount of the adjustment. Adjustments delegate updating of amount to their Originator
    # when present, but only if +locked+ is false.  Adjustments that are +locked+ will never change their amount.
    # The new adjustment amount will be set by by the +originator+ and is not automatically saved.  This makes it save
    # to use this method in an after_save hook for other models without causing an infinite recursion problem.
    #
    # order#update_adjustments passes self as the src, this is so calculations can be performed on the
    # current values. If we used source it would load the old record from db for the association
    def update!(src = nil)
      src ||= source
      return if locked?
      if originator.present?
        originator.update_adjustment(self, src)
      end
      set_eligibility
    end

    private

    def update_adjustable
      adjustable.update! if adjustable.is_a? Order
    end

  end
end

core/app/models/spree/alert.rb
module Spree
  class Alert < ActiveResource::Base
    self.site = 'http://alerts.spreecommerce.com/'
    self.format = :json

    def self.current(host)
      find(:all, :params => { :version => Spree.version,
                              :name => Spree::Config[:site_name],
                              :host => host,
                              :rails_env => Rails.env,
                              :rails_version => Rails.version })
    end
  end
end

core/app/models/spree/app_configuration.rb
# This is the primary location for defining spree preferences
#
# The expectation is that this is created once and stored in
# the spree environment
#
# setters:
# a.color = :blue
# a[:color] = :blue
# a.set :color = :blue
# a.preferred_color = :blue
#
# getters:
# a.color
# a[:color]
# a.get :color
# a.preferred_color
#
module Spree
  class AppConfiguration < Preferences::Configuration

    # Alphabetized to more easily lookup particular preferences
    preference :address_requires_state, :boolean, :default => true # should state/state_name be required
    preference :admin_interface_logo, :string, :default => 'admin/bg/spree_50.png'
    preference :admin_pgroup_per_page, :integer, :default => 10
    preference :admin_pgroup_preview_size, :integer, :default => 10
    preference :admin_products_per_page, :integer, :default => 10
    preference :allow_backorder_shipping, :boolean, :default => false # should only be true if you don't need to track inventory
    preference :allow_backorders, :boolean, :default => true
    preference :allow_checkout_on_gateway_error, :boolean, :default => false
    preference :allow_guest_checkout, :boolean, :default => true
    preference :allow_locale_switching, :boolean, :default => true
    preference :allow_ssl_in_development_and_test, :boolean, :default => false
    preference :allow_ssl_in_production, :boolean, :default => true
    preference :allow_ssl_in_staging, :boolean, :default => true
    preference :alternative_billing_phone, :boolean, :default => false # Request extra phone for bill addr
    preference :alternative_shipping_phone, :boolean, :default => false # Request extra phone for ship addr
    preference :always_put_site_name_in_title, :boolean, :default => true
    preference :auto_capture, :boolean, :default => false # automatically capture the creditcard (as opposed to just authorize and capture later)
    preference :cache_static_content, :boolean, :default => true
    preference :check_for_spree_alerts, :boolean, :default => true
    preference :checkout_zone, :string, :default => nil # replace with the name of a zone if you would like to limit the countries
    preference :company, :boolean, :default => false # Request company field for billing and shipping addr
    preference :create_inventory_units, :boolean, :default => true # should only be false when track_inventory_levels is false, also disables RMA's
    preference :default_country_id, :integer, :default => 214
    preference :default_locale, :string, :default => 'en'
    preference :default_meta_description, :string, :default => 'Spree demo site'
    preference :default_meta_keywords, :string, :default => 'spree, demo'
    preference :default_seo_title, :string, :default => ''
    preference :dismissed_spree_alerts, :string, :default => ''
    preference :last_check_for_spree_alerts, :string, :default => nil
    preference :logo, :string, :default => 'admin/bg/spree_50.png'
    preference :max_level_in_taxons_menu, :integer, :default => 1 # maximum nesting level in taxons menu
    preference :orders_per_page, :integer, :default => 15
    preference :prices_inc_tax, :boolean, :default => false
    preference :products_per_page, :integer, :default => 12
    preference :select_taxons_from_tree, :boolean, :default => false # provide opportunity to select taxons from tree instead of search with autocomplete
    preference :shipment_inc_vat, :boolean, :default => false
    preference :shipping_instructions, :boolean, :default => false # Request instructions/info for shipping
    preference :show_descendents, :boolean, :default => true
    preference :show_only_complete_orders_by_default, :boolean, :default => true
    preference :show_zero_stock_products, :boolean, :default => true
    preference :site_name, :string, :default => 'Spree Demo Site'
    preference :site_url, :string, :default => 'demo.spreecommerce.com'
    preference :tax_using_ship_address, :boolean, :default => true
    preference :track_inventory_levels, :boolean, :default => true # will not track on_hand values for variants /products

    # searcher_class allows spree extension writers to provide their own Search class
    def searcher_class
      @searcher_class ||= Spree::Core::Search::Base
    end

    def searcher_class=(sclass)
      @searcher_class = sclass
    end

  end

end

core/app/models/spree/asset.rb
module Spree
  class Asset < ActiveRecord::Base
    belongs_to :viewable, :polymorphic => true
    acts_as_list :scope => :viewable
  end
end

core/app/models/spree/calculator/flat_percent_item_total.rb
module Spree
  class Calculator::FlatPercentItemTotal < Calculator
    preference :flat_percent, :decimal, :default => 0

    def self.description
      I18n.t(:flat_percent)
    end

    def compute(object)
      return unless object.present? and object.line_items.present?
      item_total = object.line_items.map(&:amount).sum
      value = item_total * BigDecimal(self.preferred_flat_percent.to_s) / 100.0
      (value * 100).round.to_f / 100
    end
  end
end

core/app/views/spree/shared/_error_messages.html.erb
<% if target && target.errors.any? %>
  <div id="errorExplanation" class="errorExplanation" data-hook>
    <h2><%= t(:errors_prohibited_this_record_from_being_saved, :count => target.errors.count) %>:</h2>
    <p><%= t(:there_were_problems_with_the_following_fields) %>:</p>
     <ul>
     <% target.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
     </ul>
  </div>
<% end %>

core/app/views/spree/shared/_filters.html.erb
<%= form_tag '', :method => :get, :id => 'sidebar_products_search' do %>
  <% params[:search] ||= {} %>
  <%= hidden_field_tag 'per_page', params[:per_page] %>
  <% filters = @taxon ? @taxon.applicable_filters : [Spree::ProductFilters.all_taxons] %>
  <% filters.each do |filter| %>
    <% labels = filter[:labels] || filter[:conds].map {|m,c| [m,m]} %>
    <% next if labels.empty? %>
    <div class="navigation" data-hook="navigation">
      <span class="category"> <%= filter[:name] %> </span>
      <ul class="filter_choices">
        <% labels.each do |nm,val| %>
          <% label = "#{filter[:name]}_#{nm}".gsub(/\s+/,'_') %>
          <li class="nowrap">
            <input type="checkbox"
                   id="<%= label %>"
                   name="search[<%= filter[:scope].to_s %>][]"
                   value="<%= val %>"
                   <%= params[:search][filter[:scope]] && params[:search][filter[:scope]].include?(val.to_s) ? "checked" : "" %> />
            <label class="nowrap" for="<%= label %>"> <%= nm %> </label>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= submit_tag t(:search), :name => nil %>
<% end %>

core/app/views/spree/shared/_google_analytics.html.erb
<% if tracker = Spree::Tracker.current %>

  <%= javascript_tag do -%>
    var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
    document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
  <% end -%>

  <%= javascript_tag do -%>
    var pageTracker = _gat._getTracker("<%= tracker.analytics_id %>");
    pageTracker._initData();
    pageTracker._trackPageview();
  <% end -%>

  <% if flash[:commerce_tracking] %>

    <%= javascript_tag do -%>
      // report e-commerce transaction information when applicable
      pageTracker._addTrans(
      "<%= @order.number %>",    //Order Number
      "",    //Affiliation
      "<%= @order.total %>",    //Order total
      "<%= @order.adjustments.tax.sum(:amount).to_s %>",    //Tax Amount
      "<%= @order.adjustments.shipping.sum(:amount).to_s %>",    //Ship Amount
      "",    //City
      "",    //State
      ""    //Country
      );
      <% @order.line_items.each do |line_item| %>
        pageTracker._addItem("<%= @order.number %>", "<%= line_item.variant.sku %>", "<%= line_item.variant.product.name %>",
          "" /*Product Category*/, "<%= line_item.price %>", "<%= line_item.quantity %>");
      <% end %>
      pageTracker._trackTrans();
    <% end -%>

  <% end %>

<% end %>

core/app/views/spree/shared/_head.html.erb
<meta charset="utf-8">

<!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame -->
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

<title><%= title %></title>

<meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
<meta content="width=device-width, initial-scale=1.0, maximum-scale=1" name="viewport">

<%== meta_data_tags %>

<%= favicon_link_tag image_path('favicon.ico') %>

<%= stylesheet_link_tag 'store/all', :media => 'screen' %>

<%= csrf_meta_tags %>
<%= javascript_include_tag 'store/all' %>

<!--[if lt IE 9]>
<script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<%= yield :head %>

core/app/views/spree/shared/_nav_bar.html.erb
<li id="search-bar" data-hook>
  <%= render :partial => 'spree/shared/search' %>
</li>

core/app/views/spree/shared/_order_details.html.erb
<div class="row steps-data">
  
  <div class="columns alpha four">
    <h6><%= t(:shipping_address) %> <%= link_to "(#{t(:edit)})", checkout_state_path(:address) unless @order.completed? %></h6>
    <div class="address">
      <%= order.ship_address %>
    </div>
  </div>

  <div class="columns alpha four">
    <h6><%= t(:billing_address) %> <%= link_to "(#{t(:edit)})", checkout_state_path(:address) unless @order.completed? %></h6>
    <div class="address">
      <%= order.bill_address %>
    </div>
  </div>

  <div class="columns alpha four">
    <h6><%= t(:shipping_method) %> <%= link_to "(#{t(:edit)})", checkout_state_path(:delivery) unless @order.completed? %></h6>
    <div class="delivery">
      <%= order.shipping_method.name %>
    </div>
  </div>

  <div class="columns omega four">
    <h6><%= t(:payment_information) %> <%= link_to "(#{t(:edit)})", checkout_state_path(:payment) unless @order.completed? %></h6>
    <div class="payment-info">
      <% unless order.creditcards.empty? %>
        <span class="cc-type">
          <%= image_tag "creditcards/icons/#{order.creditcards.first.cc_type}.png" %>
          <%= t(:ending_in)%> <%= order.creditcards.first.last_digits %>
        </span>
        <br />
        <span class="full-name">
          <%= order.creditcards.first.first_name %>
          <%= order.creditcards.first.last_name %>
        </span>
      <% end %>
    </div>
  </div>

</div>

<hr />

<table class="index columns alpha omega sixteen" data-hook="order_details">
  
  <thead id="line-items" data-hook>
    <tr data-hook="order_details_line_items_headers">
      <th> </th>
      <th><%= t(:item_description) %></th>
      <th class="price"><%= t(:price) %></th>
      <th class="qty"><%= t(:qty) %></th>
      <th class="total"><span><%= t(:total) %></span></th>
    </tr>
  </thead>

  <tbody id="line-items" data-hook>
    <% @order.line_items.each do |item| %>
      <tr data-hook="order_details_line_item_row">
        <td data-hook="order_item_image" width="20%">
          <% if item.variant.images.length == 0 %>
            <%= small_image(item.variant.product) %>
          <% else %>
            <%= image_tag item.variant.images.first.attachment.url(:small) %>
          <% end %>
        </td>
        <td width="80%">
          <h6><%= item.variant.product.name %></h6>
          <%= truncate(item.variant.product.description, :length => 100, :omission => "...") %>
          <%= "(" + variant_options(item.variant) + ")" unless item.variant .option_values.empty? %>
        </td>
        <td class="price"><span><%= number_to_currency item.price %></span></td>
        <td class="qty"><%= item.quantity %></td>
        <td class="total"><span><%= number_to_currency (item.price * item.quantity) %></span></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot id="order-total" data-hook="order_details_total">
    <tr class="total">
      <td colspan="4"><b><%= t(:order_total) %>:</b></td>
      <td class="total"><span id="order_total"><%= number_to_currency @order.total %></span></td>
    </tr>
  </tfoot>
  <% if order.price_adjustment_totals.present? %>
    <tfoot id="price-adjustments" data-hook="order_details_price_adjustments">
      <% @order.price_adjustment_totals.keys.each do |key| %>
        <tr class="total">
          <td colspan="4"><strong><%= key %></strong></td>
          <td class="total"><span><%= number_to_currency @order.price_adjustment_totals[key] %></span></td>
        </tr>
      <% end %>
    </tfoot>
  <% end %>
  <tfoot id="subtotal" data-hook="order_details_subtotal">
    <tr class="total" id="subtotal-row">
      <td colspan="4"><b><%= t(:subtotal) %>:</b></td>
      <td class="total"><span><%= number_to_currency @order.item_total %></span></td>
    </tr>
  </tfoot>
  <tfoot id="order-charges" data-hook="order_details_adjustments">
    <% @order.adjustments.eligible.each do |adjustment| %>
    <% next if (adjustment.originator_type == 'Spree::TaxRate') and (adjustment.amount == 0) %>
      <tr class="total">
        <td colspan="4"><strong><%= adjustment.label %></strong></td>
        <td class="total"><span><%= number_to_currency adjustment.amount %></span></td>
      </tr>
    <% end %>
  </tfoot>
</table>

core/app/views/spree/shared/_products.html.erb
<%
  paginated_products = @searcher.products if params.key?(:keywords)
  paginated_products ||= products
%>
<% if products.empty? %>
  <%= t(:no_products_found) %>
<% elsif params.key?(:keywords) %>
  <h6 class="search-results-title"><%= t(:search_results, :keywords => h(params[:keywords])) %></h6>
<% end %>

<% if products.any? %>
<ul id="products" class="inline product-listing" data-hook>
  <% products.each do |product| %>
    <% if Spree::Config[:show_zero_stock_products] || product.has_stock? %>
      <li id="product_<%= product.id %>" class="columns three" data-hook="products_list_item" itemscope itemtype="http://schema.org/Product">
        <div class="product-image">
          <%= link_to small_image(product, :itemprop => "name"), product %>
        </div>
        <%= link_to product.name, product, :class => 'info', :itemprop => "name" %>
        <span class="price selling" itemprop="price"><%= number_to_currency product.price %></span>
      </li>
    <% end %>
  <% end %>
</ul>
<% end %>



<% if paginated_products.respond_to?(:num_pages)
      params.delete(:search)
      params.delete(:taxon)
%><%= paginate paginated_products %><% end %>

core/app/views/spree/shared/_search.html.erb
<% @taxons = @taxon && @taxon.parent ? @taxon.parent.children : Spree::Taxon.roots %>
<%= form_tag products_path, :method => :get do %>
  <%= select_tag :taxon,
        options_for_select([[t(:all_departments), '']] +
                              @taxons.map {|t| [t.name, t.id]},
                            @taxon ? @taxon.id : params[:taxon]) %>
  <%= search_field_tag :keywords, params[:keywords], :placeholder => t(:search) %>
  <%= submit_tag t(:search), :name => nil %>
<% end %>

core/app/views/spree/shared/_store_menu.html.erb
<li id="home-link" data-hook><%= link_to t(:home), root_path %></li>
<li id="link-to-cart" data-hook><%= link_to_cart %></li>

core/app/views/spree/shared/_taxonomies.html.erb
<nav id="taxonomies" class="sidebar-item" data-hook>
  <% get_taxonomies.each do |taxonomy| %>
    <h6 class='taxonomy-root'><%= t(:shop_by_taxonomy, :taxonomy => taxonomy.name.singularize) %></h6>
    <%= taxons_tree(taxonomy.root, @taxon, Spree::Config[:max_level_in_taxons_menu] || 1) %>
  <% end %>
</nav>